---
swagger: "2.0"
info:
  description: "LCache - Leveldb cache mechanism"
  version: "1.0.0"
  title: "RESTFUL API"
  contact:
    email: "clive.bury@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/Hndl/lcache/1.0.0"
tags:
- name: "reporting"
  description: "fetching reporting data"
- name: "developers"
  description: "Operations available to developers"
schemes:
- "https"
- "http"
paths:
  /cache/{cachename}:
    put:
      tags:
      - "developers"
      summary: "adds an cache item"
      description: "Adds an item to the cache"
      operationId: "put"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "cachename"
        in: "path"
        description: "the name of the cache to scan"
        required: true
        type: "string"
      - in: "body"
        name: "CacheItem"
        description: "Inventory item to add"
        required: false
        schema:
          $ref: "#/definitions/CachePut"
      responses:
        201:
          description: "item created"
          schema:
            type: "object"
        400:
          description: "invalid input, object invalid"
      x-swagger-router-controller: "Developers"
  /cache/{cachename}/{key}:
    get:
      tags:
      - "developers"
      summary: "searches cache using key and retrieve related value/object"
      description: "Search cache for key and retreive payload\n"
      operationId: "get"
      produces:
      - "application/json"
      parameters:
      - name: "cachename"
        in: "path"
        description: "the name of the cache to scan"
        required: true
        type: "string"
      - name: "key"
        in: "path"
        description: "the key to search for"
        required: true
        type: "integer"
      responses:
        200:
          description: "Found"
          schema:
            type: "object"
        400:
          description: "bad input parameter"
        404:
          description: "Key Not Found"
        405:
          description: "invalid METHOD"
      x-swagger-router-controller: "Developers"
    delete:
      tags:
      - "developers"
      summary: "remove the object from the specified cache"
      description: "remove the item from the specified cache.\n"
      operationId: "del"
      parameters:
      - name: "cachename"
        in: "path"
        description: "the name of the cache to scan"
        required: true
        type: "string"
      - name: "key"
        in: "path"
        description: "the key to search for"
        required: true
        type: "integer"
      responses:
        200:
          description: "Removed (even if !exist)"
        400:
          description: "bad input parameter"
        405:
          description: "invalid METHOD"
      x-swagger-router-controller: "Developers"
definitions:
  CacheItemKey:
    required:
    - "key"
    properties:
      key:
        type: "string"
        example: "mckd99488488377dhuhuhd"
    example:
      key: "mckd99488488377dhuhuhd"
  CacheItemTTL:
    properties:
      key:
        type: "integer"
    example:
      key: 0
  CacheItem:
    properties:
      key:
        type: "object"
        properties: {}
    example:
      key: "{}"
  CacheName:
    properties:
      key:
        type: "string"
        example: "order, customer, addr"
  CachePut:
    type: "object"
    required:
    - "ttl"
    properties:
      keyname:
        $ref: "#/definitions/CacheItemKey"
      ttl:
        $ref: "#/definitions/CacheItemTTL"
      payload:
        $ref: "#/definitions/CacheItem"
    example:
      payload:
        key: "{}"
      keyname:
        key: "mckd99488488377dhuhuhd"
      ttl:
        key: 0
  CacheResponse:
    type: "object"
    properties:
      cacheType:
        $ref: "#/definitions/CacheName"
      keyname:
        $ref: "#/definitions/CacheItemKey"
      payload:
        $ref: "#/definitions/CacheItem"
