---
swagger: "2.0"
info:
  description: "LCache - Leveldb cache mechanism"
  version: "1.0.1"
  title: "RESTFUL API"
  contact:
    email: "clive.bury@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/lcache"
tags:
- name: "developer"
  description: "Operations available to developers"
schemes:
- "https"
- "http"
paths:
  /cache/{cachename}/${key}:
    put:
      tags:
      - "developer"
      summary: "adds an cache item"
      description: "Adds an item to the cache"
      operationId: "set"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "cachename"
        in: "path"
        description: "the name of the cache to scan"
        required: true
        type: "string"
      - name: "key"
        in: "path"
        description: "the key to search for"
        required: true
        type: "string"
      - in: "body"
        name: "CacheItem"
        description: "Inventory item to add"
        required: false
        schema:
          $ref: "#/definitions/CachedItem"
      responses:
        201:
          description: "item created"
        400:
          description: "invalid input, object invalid"
      x-swagger-router-controller: "Developer"
  /cache/{cachename}/{key}:
    get:
      tags:
      - "developer"
      summary: "searches cache using key and retrieve related value/object"
      description: "Search cache for key and retreive payload\n"
      operationId: "fetch"
      produces:
      - "application/json"
      parameters:
      - name: "cachename"
        in: "path"
        description: "the name of the cache to scan"
        required: true
        type: "string"
      - name: "key"
        in: "path"
        description: "the key to search for"
        required: true
        type: "string"
      responses:
        200:
          description: "Found"
          schema:
            type: "object"
        400:
          description: "bad input parameter"
        404:
          description: "Key Not Found"
      x-swagger-router-controller: "Developer"
    delete:
      tags:
      - "developer"
      summary: "remove the object from the specified cache"
      description: "remove the item from the specified cache.\n"
      operationId: "del"
      parameters:
      - name: "cachename"
        in: "path"
        description: "the name of the cache to scan"
        required: true
        type: "string"
      - name: "key"
        in: "path"
        description: "the key to search for"
        required: true
        type: "string"
      responses:
        200:
          description: "Removed (even if !exist)"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Developer"
definitions:
  CachedItem:
    required:
    - "payload"
    properties:
      payload:
        type: "string"
    example:
      payload: "payload"
